server:
  port: 9093  
 
eureka:
  instance:
    appname: swaggerApp
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
swagger: 
  config: 
    refreshrate: 5000