spring:
  application:
    name: person
server:
  port: 9091 
eureka: 
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost 
